# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'CodeTestsRewrite' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for CodeTestsRewrite
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Alamofire'
  pod 'RxAlamofire'

  target 'CodeTestsRewriteTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Nimble'
    pod 'Quick'
  end

  target 'CodeTestsRewriteUITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Nimble'
    pod 'Quick'
  end
  
end

